# Generated by Django 3.2.25 on 2025-05-14 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('journal', models.CharField(max_length=500, verbose_name='Journal')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('month', models.IntegerField(blank=True, help_text='Month (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month')),
                ('day', models.IntegerField(blank=True, help_text='Day (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('highlighted_authors', models.TextField(blank=True, help_text='Comma-separated list of author names to be highlighted', verbose_name='Highlighted Authors')),
                ('corresponding_authors', models.TextField(blank=True, help_text='Comma-separated list of corresponding author names', verbose_name='Corresponding Authors')),
                ('bibtex_key', models.CharField(blank=True, max_length=100, unique=True, verbose_name='BibTeX Key')),
                ('raw_bibtex', models.TextField(blank=True, verbose_name='Raw BibTeX')),
                ('bibtex_type', models.CharField(blank=True, max_length=50, verbose_name='BibTeX Type')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('keywords', models.TextField(blank=True, help_text='Keywords separated by commas', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-year', '-order'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('orcid_client_id', 'ORCID Client ID'), ('orcid_client_secret', 'ORCID Client Secret'), ('orcid_access_token', 'ORCID Access Token'), ('scholar_proxy', 'Google Scholar Proxy'), ('sync_interval', 'Sync Interval'), ('github_token', 'GitHub Token'), ('researchgate_token', 'ResearchGate Token'), ('linkedin_token', 'LinkedIn Token'), ('highlighted_authors', 'Highlighted Authors')], max_length=50, verbose_name='Category')),
                ('value', models.TextField(verbose_name='Value')),
                ('description', models.TextField(blank=True, help_text='Description of this configuration', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', help_text='Name to be displayed on the homepage', max_length=100, verbose_name='Display Name')),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID ID (e.g., 0000-0000-0000-0000)', max_length=50)),
                ('google_scholar_id', models.CharField(blank=True, help_text='Google Scholar ID', max_length=100)),
                ('github_username', models.CharField(blank=True, help_text='GitHub Username', max_length=100)),
                ('researchgate_url', models.URLField(blank=True, help_text='ResearchGate Profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn Profile URL')),
                ('auto_sync_orcid', models.BooleanField(default=False, help_text='Automatically sync publications from ORCID')),
                ('auto_sync_google_scholar', models.BooleanField(default=False, help_text='Automatically sync publications from Google Scholar')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
