# Generated by Django 3.2.25 on 2025-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='DOI'),
        ),
    ]
