# Generated by Django 3.2.25 on 2025-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0002_alter_publication_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publication_images/', verbose_name='Image'),
        ),
    ]
