# Generated by Django 3.2.25 on 2025-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0004_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='bibtex_key',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='BibTeX Key'),
        ),
    ]
