# Generated by Django 3.2.25 on 2026-07-17 13:45

from django.db import migrations, models


def remove_legacy_system_ai_config(apps, schema_editor):
    SystemConfig = apps.get_model('myHomePage', 'SystemConfig')
    SystemConfig.objects.filter(category='ai_config').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0014_profile_zh_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('provider', models.CharField(blank=True, default='', max_length=100, verbose_name='Provider')),
                ('base_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Base URL')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API Key')),
                ('model_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Model')),
                ('config_json', models.TextField(blank=True, default='', verbose_name='Configuration JSON')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.RunPython(remove_legacy_system_ai_config, migrations.RunPython.noop),
    ]
