# Generated by Django 3.2.25 on 2026-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0016_auto_20260717_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='enable_detail',
            field=models.BooleanField(default=False, verbose_name='Enable Detail Page'),
        ),
        migrations.AddField(
            model_name='research',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Maximum 500 words.', verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='research',
            name='summary_zh',
            field=models.TextField(blank=True, default='', help_text='Maximum 500 words.', verbose_name='Summary (Chinese)'),
        ),
    ]
