# Generated by Django 3.2.25 on 2026-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0017_auto_20260717_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Check At'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='last_check_message',
            field=models.TextField(blank=True, default='', verbose_name='Last Check Message'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='last_check_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Last Check OK'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI Official'), ('openai_compatible', 'OpenAI Compatible'), ('glm_bigmodel', 'GLM BigModel'), ('deepseek', 'DeepSeek'), ('scnet_qwen', 'SCNet Qwen'), ('scnet_minimax', 'SCNet MiniMax'), ('felo_ppt', 'Felo PPT API')], default='openai_compatible', max_length=100, verbose_name='Provider'),
        ),
    ]
