# Generated by Django 3.2.25 on 2026-07-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0018_auto_20260717_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='publication_files/', verbose_name='File')),
                ('display_text', models.CharField(choices=[('PDF', 'PDF'), ('Slides', 'Slides'), ('Code', 'Code'), ('Data', 'Data'), ('Supplement', 'Supplement'), ('Other', 'Other')], default='PDF', max_length=80, verbose_name='Display Text')),
                ('custom_display_text', models.CharField(blank=True, default='', max_length=80, verbose_name='Custom Display Text')),
                ('access_key', models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myHomePage.publication', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Publication File',
                'verbose_name_plural': 'Publication Files',
                'ordering': ['order', 'id'],
            },
        ),
    ]
