# Generated by Django 3.2.25 on 2026-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0019_publicationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='detail_content',
            field=models.TextField(blank=True, default='', verbose_name='Detail Content'),
        ),
        migrations.AddField(
            model_name='publication',
            name='detail_content_zh',
            field=models.TextField(blank=True, default='', verbose_name='Detail Content (Chinese)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='enable_detail',
            field=models.BooleanField(default=False, verbose_name='Enable Detail Page'),
        ),
    ]
