# Generated by Django 3.2.25 on 2026-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0020_auto_20260720_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfile',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publicationfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publication_files/', verbose_name='File'),
        ),
    ]
