# Generated by Django 3.2.25 on 2026-07-20 09:35

from django.db import migrations, models
import django.utils.timezone


def create_resource_retention_config(apps, schema_editor):
    SystemConfig = apps.get_model('myHomePage', 'SystemConfig')
    SystemConfig.objects.get_or_create(
        category='resource_log_retention_hours',
        defaults={
            'value': '168',
            'description': 'How long resource monitor logs are retained, in hours.',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0021_auto_20260720_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('cpu_percent', models.FloatField(blank=True, null=True, verbose_name='CPU Percent')),
                ('memory_percent', models.FloatField(blank=True, null=True, verbose_name='Memory Percent')),
                ('memory_total', models.BigIntegerField(blank=True, null=True, verbose_name='Memory Total')),
                ('memory_used', models.BigIntegerField(blank=True, null=True, verbose_name='Memory Used')),
                ('memory_available', models.BigIntegerField(blank=True, null=True, verbose_name='Memory Available')),
                ('disk_percent', models.FloatField(blank=True, null=True, verbose_name='Disk Percent')),
                ('disk_total', models.BigIntegerField(blank=True, null=True, verbose_name='Disk Total')),
                ('disk_used', models.BigIntegerField(blank=True, null=True, verbose_name='Disk Used')),
                ('disk_free', models.BigIntegerField(blank=True, null=True, verbose_name='Disk Free')),
                ('network_sent', models.BigIntegerField(blank=True, null=True, verbose_name='Network Sent')),
                ('network_received', models.BigIntegerField(blank=True, null=True, verbose_name='Network Received')),
                ('upload_speed', models.FloatField(blank=True, null=True, verbose_name='Upload Speed')),
                ('download_speed', models.FloatField(blank=True, null=True, verbose_name='Download Speed')),
                ('process_memory_rss', models.BigIntegerField(blank=True, null=True, verbose_name='Process Memory RSS')),
                ('process_threads', models.IntegerField(blank=True, null=True, verbose_name='Process Threads')),
            ],
            options={
                'verbose_name': 'Resource Metric Log',
                'verbose_name_plural': 'Resource Metric Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='category',
            field=models.CharField(choices=[('enable_chinese', 'Enable Chinese'), ('cards_per_page', 'Cards Per Page'), ('orcid_client_id', 'ORCID Client ID'), ('orcid_client_secret', 'ORCID Client Secret'), ('orcid_access_token', 'ORCID Access Token'), ('scholar_proxy', 'Google Scholar Proxy'), ('sync_interval', 'Sync Interval'), ('github_token', 'GitHub Token'), ('researchgate_token', 'ResearchGate Token'), ('linkedin_token', 'LinkedIn Token'), ('highlighted_authors', 'Highlighted Authors'), ('footer_items', 'Footer Items'), ('resource_log_retention_hours', 'Resource Log Retention Hours')], max_length=50, verbose_name='Category'),
        ),
        migrations.RunPython(create_resource_retention_config, migrations.RunPython.noop),
    ]
