# Generated by Django 3.2.25 on 2026-07-20 09:45

from django.db import migrations, models


def migrate_felo_ppt_configs(apps, schema_editor):
    AIConfig = apps.get_model('myHomePage', 'AIConfig')
    AIConfig.objects.filter(provider='felo_ppt').update(provider='openai_compatible', is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('myHomePage', '0022_auto_20260720_1735'),
    ]

    operations = [
        migrations.RunPython(migrate_felo_ppt_configs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI Official'), ('openai_compatible', 'OpenAI Compatible'), ('glm_bigmodel', 'GLM BigModel'), ('deepseek', 'DeepSeek'), ('scnet_qwen', 'SCNet Qwen'), ('scnet_minimax', 'SCNet MiniMax')], default='openai_compatible', max_length=100, verbose_name='Provider'),
        ),
    ]
